@startuml
'https://plantuml.com/class-diagram

interface IHandler {
-Boolean handler()
}

class ConcreteHandler {
-Boolean handler()
}

class HandlerChain {
+List[] IHandler
+Constructor NewHandlerChain()
+AddHandler(IHandler)
+Handle()
}

IHandler <|.. ConcreteHandler

@enduml
