@startuml
'https://plantuml.com/class-diagram

interface AbstractProduct {
+ Show()
}

class ConcreteProduct {
+ Show()
}

interface AbstractFactory {
+ NewProduct(): abstractProduct
}

class ConcreteFactory {
+ NewProduct(): concreteProduct
}

AbstractProduct <|.. ConcreteProduct
AbstractFactory <|.. ConcreteFactory

@enduml
