@startuml
'https://plantuml.com/class-diagram

interface AbstractProduct {
+ Show()
}

class ConcreteProduct {
+ Show()
}

interface AbstractFactory {
+ AbstractProduct NewProduct()
}

class ConcreteFactory {
+ Product NewProduct(): concreteProduct
}

AbstractProduct <|.. ConcreteProduct
AbstractFactory <|.. ConcreteFactory

@enduml
