@startuml
'https://plantuml.com/class-diagram

interface ITemplate {
+Fun1()
+Fun2()
+Result()
}

class TemplateFather {
-ITemplate template
+Constructor NewTemplateFather(ITemplate)
+Result()
}

class ConcreteTemplate {
TemplateFather
+Fun1()
+Fun2()
}

@enduml
